//User Error
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const VALIDATE_SESSION_ERROR = 'VALIDATE_SESSION_ERROR';
export const CHANGE_LOGIN_FLAG_ERROR = 'CHANGE_LOGIN_FLAG_ERROR';
export const CLEAR_CLIENT_ERROR = 'CLEAR_CLIENT_ERROR';
