//User Error
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const VALIDATE_SESSION_ERROR = 'VALIDATE_SESSION_ERROR';

//Rating Types
export const GET_RATING_ERROR = 'GET_RATING_ERROR';
export const LIST_RATING_ERROR = 'LIST_RATING_ERROR';
export const CREATE_RATING_ERROR = 'CREATE_RATING_ERROR';
export const EXCLUDE_RATNG_ERROR = 'EXCLUDE_RATNG_ERROR';
export const UPDATE_RATING_ERROR = 'UPDATE_RATING_ERROR';