//User Error
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const VALIDATE_SESSION_ERROR = 'VALIDATE_SESSION_ERROR';

//Rating Error
export const GET_RATING_ERROR = 'GET_RATING_ERROR';
export const LIST_RATING_ERROR = 'LIST_RATING_ERROR';
export const CREATE_RATING_ERROR = 'CREATE_RATING_ERROR';
export const EXCLUDE_RATNG_ERROR = 'EXCLUDE_RATNG_ERROR';
export const UPDATE_RATING_ERROR = 'UPDATE_RATING_ERROR';

//Account Error
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR'; 
export const GET_ACCOUNT_ERROR = 'GET_ACCOUNT_ERROR'; 
export const GET_WITH_TOKEN_ACCOUNT_ERROR = 'GET_WITH_TOKEN_ACCOUNT_ERROR'; 
export const DELETE_ACCOUNT_ERROR = 'DELETE_ACCOUNT_ERROR'; 
export const BATCH_DELETE_ACCOUNT_ERROR = 'BATCH_DELETE_ACCOUNT_ERROR';
export const UPDATE_ACCOUNT_ERROR = 'UPDATE_ACCOUNT_ERROR'; 
export const LIST_EMPLOYEES_ACCOUNT_ERROR = 'LIST_EMPLOYEES_ACCOUNT_ERROR'; 
export const LIST_ADMINS_ACCOUNT_ERROR = 'LIST_ADMINS_ACCOUNT_ERROR'; 