//User Types
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const VALIDATE_SESSION = 'VALIDATE_SESSION';
export const CLEAR_USER_ERROR = 'CLEAR_USER_ERROR';
export const CLEAR_USER = 'CLEAR_USER';

//Rating Types
export const GET_RATING = 'GET_RATING';
export const LIST_RATING = 'LIST_RATING';
export const CREATE_RATING = 'CREATE_RATING';
export const EXCLUDE_RATNG = 'EXCLUDE_RATNG';
export const UPDATE_RATING = 'UPDATE_RATING';

//Account Types
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'; 
export const GET_ACCOUNT = 'GET_ACCOUNT'; 
export const GET_WITH_TOKEN_ACCOUNT = 'GET_WITH_TOKEN_ACCOUNT'; 
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'; 
export const BATCH_DELETE_ACCOUNT = 'BATCH_DELETE_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'; 
export const LIST_EMPLOYEES_ACCOUNT = 'LIST_EMPLOYEES_ACCOUNT'; 
export const LIST_ADMINS_ACCOUNT = 'LIST_ADMINS_ACCOUNT'; 
export const INCREMENT_ACCOUNT_RATING_COUNTER = 'INCREMENT_ACCOUNT_RATING_COUNTER';
export const DECREMENT_ACCOUNT_RATING_COUNTER = 'DECREMENT_ACCOUNT_RATING_COUNTER';